---
cops_dbsmartbackup_confs:
  db:
    conf_path: /srv/backups/db.conf
    keep_lasts: 1
    type: postgresql
    keep_days: 2
    keep_logs: 7
    _periodicity: "0 3 * * *"
    free_form: |
      export HOST="{{cops_flask_db_host}}"
      export PORT="{{cops_flask_db_port}}"
      export DBNAMES="{{cops_flask_db_name}}"
      export PASSWORD="{{cops_flask_db_password}}"
      export DBUSER="{{cops_flask_db_user}}"
      export PGUSER="$DBUSER"
      export RUNAS=""
      export PGPASSWORD="$PASSWORD"
