---
cops_flask_name: flaskinstance
cops_flask_project_module_name: "{{cops_flask_name}}"
cops_flask_settings_module_name: "settings"
cops_flask_settings_module: "{{cops_flask_project_module_name}}.{{cops_flask_settings_module_name.replace('.', '/')}}.instances.{{cops_flask_deploy_env}}"
cops_flask_deploy_env: "dev"
cops_flask_docker_image_tag: "{{cops_flask_name}}"
cops_flask_default_docker_tag: "latest"
cops_flask_docker_tag: "{{cops_flask_default_docker_tag}}"
cops_flask_tld_domain: example.com
cops_flask_mail_domain: "{{ cops_flask_tld_domain }}"
cops_flask_default_gitref: "master"
cops_flask_gitref: "{{cops_flask_default_gitref}}"
cops_flask_dir: "/srv/docker/{{cops_flask_name}}"
cops_flask_hostname: "{{cops_flask_deploy_env}}-{{cops_flask_name}}.{{cops_flask_tld_domain}}"
cops_flask_alternate_hostnames: [".{{cops_flask_tld_domain}}"]
cops_flask_secret_key: "SuperSecret"
cops_flask_gateway: "{{ ansible_default_ipv4.address}}"
cops_flask_composename: "{{cops_flask_name}}"
cops_flask_db_host: "db"
cops_flask_db_port: "5432"
cops_flask_db_user: "secretJFCxwPHz99R9jIi"
cops_flask_db_password: "secret4gzQNe3c8851VOJ"
cops_flask_db_name: "{{cops_flask_name}}"
cops_flask_devmode: False
cops_flask_build_args: "--no-cache flask cron"
# backup could be remove in a-while when we have redeployed it everywhere
cops_flask_restarted_services_default: "db redis flask nginx backup cron"
cops_flask_restarted_services: "{{cops_flask_restarted_services_default}}"
cops_flask_purge_volumes: []
cops_flask_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_flask_build: false
cops_flask_pull: true
cops_flask_registries: []
#- {registry: registry.foo.net, username: foo, password: bar}
cops_flask_compose_files: [docker-compose.yml, docker-compose-prod.yml]
cops_flask_dc:
  docker-compose {% for i in cops_flask_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_flask_composename}}"
cops_flask_default_from_email: noreply@{{cops_flask_hostname}}
cops_flask_server_email: "{{cops_flask_default_from_email}}"
cops_flask_mailcatcher_user: mailcatcher
cops_flask_mailcatcher_password: mailcatcher
cops_flask_server_email: "{{cops_flask_default_from_email}}"
cops_flask_email_server: mailcatcher
cops_flask_email_host_user: ''
cops_flask_email_host_password: ''
cops_flask_email_host_port: 1025
cops_flask_email_use_tls: 'no'
cops_flask_http_protect_user: "root"
cops_flask_http_protect_password: "rootroot"
cops_flask_redis_url: "redis://redis:6379/1"
cops_flask_hosts_whitelist: "{{(
    [cops_flask_hostname, '0.0.0.0', '.{0}'.format(cops_flask_hostname)]+
    cops_flask_alternate_hostnames
  )|join('-|_')}}"
cops_flask_sentry_tags: ["env:{{cops_flask_deploy_env}}"]
cops_flask_sentry_dsn: ''
cops_flask_docker_env_freeform: |-
  {{ cops_flask_docker_env_defaults}}
  {{ cops_flask_docker_env_extra}}
cops_flask_gunicorn_class: "sync"
cops_flask_gunicorn_extra_args: ""
cops_flask_env: production
# can be 'all' to backup all
cops_flask_backuped_dbs: "{{cops_flask_db_name}}"
cops_flask_docker_env_defaults: |-
  # cors
  FLASK__CORS_ORIGIN_WHITELIST={{cops_flask_hosts_whitelist}}
  FLASK__ALLOWED_HOSTS={{cops_flask_hosts_whitelist}}
  {% if cops_flask_devmode %}
  FLASK__CORS_ORIGIN_ALLOW_ALL=y
  FLASK__DEBUG=y
  {% endif %}
  FLASK__DEFAULT_FROM_EMAIL={{ cops_flask_default_from_email }}
  FLASK__SERVER_EMAIL={{ cops_flask_server_email }}
  FLASK__EMAIL_HOST={{cops_flask_email_server}}
  {% if "{0}".format(cops_flask_email_use_tls).lower() in ['yes', 'no'] %}
  FLASK__EMAIL_USE_TLS={{cops_flask_email_use_tls}}
  {% endif %}
  FLASK__EMAIL_PORT={{cops_flask_email_host_port}}
  FLASK__EMAIL_HOST_USER={{cops_flask_email_host_user}}
  FLASK__EMAIL_HOST_PASSWORD={{cops_flask_email_host_password}}
# free form for params inside dockerenv
cops_flask_dotenv: |-
  FLASK__REDIS_URL={{cops_flask_redis_url}}
  FLASK__DEPLOY_ENV={{cops_flask_deploy_env}}
  FLASK__HTTP_PROTECT_USER={{cops_flask_http_protect_user}}
  FLASK__HTTP_PROTECT_PASSWORD={{cops_flask_http_protect_password}}
  {% if cops_flask_sentry_dsn %}
  SENTRY_DSN={{cops_flask_sentry_dsn}}
  SENTRY_RELEASE={{cops_flask_docker_tag}}
  SENTRY_ENVIRONMENT={{cops_flask_deploy_env}}
  {% endif %}
  REDIS_URL={{cops_flask_redis_url}}
  DBS_DBNAMES={{cops_flask_backuped_dbs}}
  MAILCATCHER_USER={{cops_flask_mailcatcher_user}}
  MAILCATCHER_PASSWORD={{cops_flask_mailcatcher_password}}
  # This need to be changed in production
  FLASK_ENV={{cops_flask_env}}
  SECRET_KEY={{ cops_flask_secret_key }}
  # gunicorn
  GUNICORN_CLASS={{cops_flask_gunicorn_class}}
  GUNICORN_EXTRA_ARGS={{cops_flask_gunicorn_extra_args}}
  # db
  POSTGRES_HOST={{ cops_flask_db_host }}
  POSTGRES_PORT={{ cops_flask_db_port }}
  POSTGRES_USER={{ cops_flask_db_user }}
  POSTGRES_DB={{ cops_flask_db_name }}
  POSTGRES_PASSWORD={{cops_flask_db_password }}
  PGPASSWD={{cops_flask_db_password }}
  FLASK_SETTINGS_MODULE={{cops_flask_settings_module}}
  FLASK_NAME={{ cops_flask_name }}
  COMPOSE_PROJECT_NAME={{cops_flask_composename}}
  CONTROL_COMPOSE_FILES={{cops_flask_compose_files|join(' ')}}
  CI_COMMIT_SHA={{cops_flask_gitref}}
  FLASK_IMAGE={{ cops_flask_docker_image }}
  FLASK_IMAGE_VERSION={{cops_flask_docker_tag}}
  # left for retrocompat
  FLASK_PY_VER={{ cops_flask_py_ver }}
  APP_TYPE=flask
cops_flask_dotenv_extra: ""
# free form for params inside dockerenv
cops_flask_docker_env_extra: ""
# free form for params inside local.py
cops_flask_localpy_extra: ""
# Normally playbook is in ./.ansible/playbooks
cops_flask_code_dir: "{{playbook_dir}}/../.."
cops_flask_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", ".tox",
    "--exclude", ".env",
    "--exclude", "docker.env"]
cops_flask_backup_postgresql: "{{'5432' == '{0}'.format(cops_flask_db_port)}}"
cops_flask_backup_paths_to_backup:
- "{{cops_flask_dir}}"
cops_flask_backup_docker_volumes: []
cops_flask_backup_docker_volumes_: |-
  {% set res = [] %}
  {% for i in cops_flask_backup_docker_volumes %}
  {% set  _ = res.append('_'.join([cops_flask_composename, i])) %}
  {% endfor %}
  {{ res | to_json }}
cops_flask_backup_pgdump_urls:
- name: "{{cops_flask_db_name}}"
  url: "postgres://{{
      cops_flask_db_user}}:{{cops_flask_db_password}}@{{
        cops_flask_db_host}}:{{cops_flask_db_port}}/{{
          cops_flask_db_name}}"
  docker_dir: "{{cops_flask_dir}}"
  docker_service: backup
  docker_compose: "{{cops_flask_dc}}"
# left for retrocompat
cops_flask_py_ver: "3.7"
